[gcp_service_account]
type = "service_account"
project_id = "monitoring-disposisi"
private_key_id = "f31cc9cb948ff43b8cda7782678bdaa266a5ed3e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDiK+falpkESGuT
megqoL9kW/7nMaVoXiUe4l2dqpNiMwJbjaMRNzTTpQ4AKBgCZKiv2co28mFIXakK
Us8u8GqaUItgdu7iXhUPzbwttCHt/7c+9KcfAssJ3OzxbF8RmouXr98KQVtsc5W+
uc5ntrBQDlRjVD3Lfce6W6CRkCnNy4Jbc3+ukkxzmOEnXN8kWvBnskW3TxNSHUXd
Q4BkdvUy+JtOvpdNzVBCZV3DK4vB1K5qCWi1Xbobga9e/kxVnmfVVFZY9qwCVnf+
gaMQdFBA1ugfrls4W3m3KVb+ulWNDQosnW6t+3+nBgyzaEG4YNP6rO0GI6RatpN8
2GZm34z5AgMBAAECggEAC+FXh/ViK0XslK/AcMDJ3OkyLg2/DQjo9ULZvQbxP/bC
+HErsCNQvI9OeXahsDp+W+JaS2GW95in4PlxlZseVmXFtHb63Fwpyg86A8KTB6/n
fcCXKLtaU/XNYm8ZXVDbZUfhNOYy+bLmmkKjU3JWt5XRG/iYWGCOhbz7ZboHYB5n
trO1sUL1BoZxXM2X6xGmt4So/fkHqBww30eVX19qm7GGGe54m64OHLdiVJIsQMH6
RgHINBl1MYX/fR+bkSGAOfq5qAu5jUAWIUWCsZUUEuZTeE/OOzvErKpEqnzQGY0t
neGiUIqvRUNhMSPjwVzR0Fe2hH5qplgEpfGgrZwkWwKBgQD8yd4/XuhWT/5bg4FH
atLC18qFLW83W+FT2jCKt8NM72K73xxaBXxBtQRuC9/faiXID3CT+m+CzCaHzR4z
WaBoVaxalLwRmLecgr+ViJeUnZ89e+F5f6Vm+VeabDws+VKkZ7ylfac808z+Cvyq
DxO3IOLeW1xwqW9gbrHo1hShYwKBgQDlC3jjlKnBFM6ydq9BQ4winjFCvbR1N4Aa
DzxoFnbBDnEwbCIbNlhvNLyDS7oeIB2gVz8YMArvqT+jhsmzH9Sy+p8fvSLMnEoq
Pv3huRvIUX+MsqcZ8C/tJ7f7WqWHLcpyoTOdClQzXHOV42wobi0C4qyB/byYI7/3
06RhcCj08wKBgQDsgt7awax1nRBphOd+71ZUEFweMH0++UsgDiOelgI3SD5DcqLv
IvS38Wo8oAWM3Z6NyMxW11hfsyxVoLch6jhnhcjlUwWHHTClUbt4Z70SwkrL1s0F
xUT2zFGHXL8MgRUuVxSsbZz8D1pbUeJGJicXDsDUs/wQOKbJPahdJXdV6wKBgAVL
dZj1N9Nh0sFnYvfEQvoN5B+h2QkYplpz3baeRlKCLfWrmkI8yGCRvIXge0X1AhpR
ygCaI7aUmAcEt6bvZnBYwNLwAVzvg/tkB2Rvbgf8clFjU9+SoNj/oQ4rc0Yjtdle
hp3rvjSNv5JIdpicq2e0q745imGN+gMVnmguOpQnAoGBAMYbibDciV2Lqdo4JgB4
+CUnG21/fATeThQoPE/F8oVl8hvfuuFvtSGbQ7BF+/l41+nIRRust4hcL5CuIxUO
GdofBZHwtB2ScdMaj9l06ZcEfvPnBY9qNzy8qq5Rvrh0bqnQIjn06tlikYic9Vhd
0VG3qcwqcXQF0tJGrHVjYBVa
-----END PRIVATE KEY-----"""
client_email = "monitoring-disposisi-bot@monitoring-disposisi.iam.gserviceaccount.com"
client_id = "110298508095718145896"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/monitoring-disposisi-bot%40monitoring-disposisi.iam.gserviceaccount.com"

[gsheets]
spreadsheet_name = "monitoring_disposisi"
